# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SacKinghacks2018' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  # Pods for SacKinghacks2018

  target 'SacKinghacks2018Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SacKinghacks2018UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
